---
- name: War File Deploy tomcat tomcat
  hosts: servera.example.com
  become: true
  tasks:
    - name: Test url
      uri:
        url: http://servera.example.com:8080/warfile1/
        status_code: 200
        return_content: true
      register: url_status
      ignore_errors: true
    - name: Stop tomcat server
      service:
        name: tomcat
        state: stopped
    - name: delete existing war file
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/tomcat9/webapps/tim.war
        - /usr/local/tomcat9/webapps/tim
    #- name: Download new deployment file
    # get_url:
    #    url: https://github.com/eswiftt/tomcat/raw/main/warsfiles/hills.war
    #    dest: /usr/local/tomcat9/webapps/warfile1.war
    - name: Copy a new war file
      copy:
        src: warsfiles/hills.war
        dest: /usr/local/tomcat9/webapps/
    - name: set file permissions
      file:
        path: /usr/local/tomcat9/webapps/hills.war
        owner: tomcat
        group: tomcat
      notify: start tomcat
  handlers:
    - name: start tomcat
      service:
        name: tomcat
        state: started

- name: Testing the URL after Deployment
  hosts: localhost
  become: false
  tasks:
    - name: Check URL status
      uri:
        url: http://servera.example.com:8080/hills/
        return_content: true
        status_code: 200
      register: deployed_url
    - name: Display URL after deployment
      debug:
        msg: "Deployment success"
      when: deployed_url.status == 200